### ISSUE TITLE
Regarding the diffusion process

### ISSUE THREAD

**Issue by pjd96** [QWTforGithub/PUDM#15]
Hi. The file containing the model configuration `pointnet2_with_pcld_condition.py` does not seem to mention anywhere about diffusion process. Even the file `pointwise_net.py` containing diffusion related methods is not referenced anywhere. Can you please explain? Thanks in advance.

**Comment by QWTforGithub** [comment]
Hi. pointnet2_with_pcld_condition.py and pointwise_net.py do not involve the diffusion process $$q$$, because the diffusion process of DDPMs is predefined, not trainable. These two files essentially build the generation process $$p_\theta$$ of DDPMs.$$p_\theta$$ is actually denoising, learning  the inverse process of $$q$$.

**Comment by QWTforGithub** [comment]
Hi, if there are any issues that need to be discussed and clarified, we can continue to communicate.

**Comment by QWTforGithub** [comment]
Hi, you are right, pointwise_net.py is indeed a useless file. The current network architecture does not require it. I deleted this file and ran the training and testing commands with absolutely no effect. I will remove it from this project. Thanks!
