### ISSUE TITLE
Inquiry Regarding the Comparison Between mid_interpolate and condition ddpm Methods

### ISSUE THREAD

**Issue by xwqtju** [QWTforGithub/PUDM#6]
Hi,

 I have recently been reading your paper with great interest, particularly the section discussing the point cloud upsampling methods. In my experiments, I observed that the upsampled point clouds generated using the mid_interpolate method have surpassed the results of the condition ddpm method in terms of evaluation metrics.

Given this, I would like to ask for your guidance on one question: In this scenario, what is the significance of continuing to use the condition ddpm method for point cloud processing? Are there specific application scenarios or datasets where the condition ddpm method still holds unique advantages?

I look forward to your response and greatly appreciate your help!

Best regards,

**Comment by QWTforGithub** [comment]
Hi, thank you for your attention to our work. Point cloud upsampling is a low-level task that serves downstream tasks. We found that although directly using the mid_interpolate method does have more impressive quantitative results, the qualitative results will have more holes and non-uniformity (such as Grad_PU) and are sensitive to noise. This is not very meaningful for downstream tasks. Therefore, we consider using it as a guide for DDPM in the inference phase instead of directly using the mid_interpolate method to generate results.
In fact, **we found through experiments that continuing to train DDPM will get better qualitative results, but it also requires more training cost**. We believe that low-level tasks should not have a large computational cost in both training and inference phases, so we train for 1000 epochs.
