### ISSUE TITLE
Upsampling to 128x

### ISSUE THREAD

**Issue by juhha1** [QWTforGithub/PUDM#8]
Hi! Thanks for sharing your interesting research. I enjoyed reading your paper and codes.

And I'd like to ask how I can sample for 128x experiments.
I was able to upsample 4x and 16x by simply changing "R", but for 128x, even 40GB GPU throws "CUDA out of memory". 
I guess there is some other way around upsampling this high scaling factor.

Can you share your code for generating this?

Thanks again!

**Comment by QWTforGithub** [comment]
> Hi! Thanks for sharing your interesting research. I enjoyed reading your paper and codes.
> 
> And I'd like to ask how I can sample for 128x experiments. I was able to upsample 4x and 16x by simply changing "R", but for 128x, even 40GB GPU throws "CUDA out of memory". I guess there is some other way around upsampling this high scaling factor.
> 
> Can you share your code for generating this?
> 
> Thanks again!

Thank you very much for your interest in our work. If you want to perform 128x upsampling, just run python example_samples.py --dataset PUGAN --R 128 --step 30 --example_file ./example/KITTI.xyz. However, as you said, for 124231 points, it can only perform up to 16x for a 40G GPU (2048 points can run in an NVIDIA 3090 GPU). This is essentially due to the inclusion of KNN in the code. If you really want to perform 128x, I would suggest, not to execute the code on the GPU, but on the CPU. But this will make the code run very slowly if you don't care.

**Comment by QWTforGithub** [comment]
In the next version, we will consider using the grid pooling instead of KNN to reduce the memory cost .

**Comment by juhha1** [comment]
Thanks for your quick reply!
Last 2 questions: For your paper, did you use CPU for 128x? Did you also use CPU for Grad-PU's 128x?

**Comment by QWTforGithub** [comment]
> Thanks for your quick reply! Last 2 questions: For your paper, did you use CPU for 128x? Did you also use CPU for Grad-PU's 128x?

Hi, I did not perform 128x upsampling using CPU, since an NVIDIA 3090 GPU is sufficient for 128x upsampling of 2048 points. Do you mean to perform 128x upsampling on KITTI? If you are currently writing a paper, I think performing 128x upsampling on PU1K or PUGAN (2048 points) is sufficient.

**Comment by juhha1** [comment]
Oh, I am sorry! I was doing batch inferencing. When I reduce the batch size, it worked!
Thanks again and I will close this issue!

**Comment by QWTforGithub** [comment]
> Oh, I am sorry! I was doing batch inferencing. When I reduce the batch size, it worked! Thanks again and I will close this issue!

Hi, thanks for reminding me. I will update the readme with this information.
